#!/usr/bin/env tsx

/**
 * Test IremboPay Configuration Script
 *
 * This script tests your IremboPay setup with the auto-generated product code
 *
 * Run with: npx tsx scripts/test-irembopay-config.ts
 */

console.log('🧪 Testing IremboPay Configuration...\n');

// Check environment variables
const requiredEnvVars = {
  IREMBO_SECRET_KEY: process.env.IREMBO_SECRET_KEY,
  IREMBO_PAYMENT_ACCOUNT_ID: process.env.IREMBO_PAYMENT_ACCOUNT_ID,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
};

console.log('📋 Environment Variables Check:');
console.log('='.repeat(50));

let allConfigured = true;

Object.entries(requiredEnvVars).forEach(([key, value]) => {
  const status = value ? '✅' : '❌';
  const displayValue = value
    ? key.includes('SECRET')
      ? '[CONFIGURED]'
      : value
    : '[NOT SET]';

  console.log(`${status} ${key}: ${displayValue}`);

  if (!value) allConfigured = false;
});

console.log('\n🎯 Configuration Status:');

if (allConfigured) {
  console.log('✅ All required environment variables are configured!');

  console.log('\n📝 Your Setup:');
  console.log(
    `   Payment Account: ${
      process.env.IREMBO_PAYMENT_ACCOUNT_ID || 'PI-bd12658823 (default)'
    }`
  );
  console.log(`   App URL: ${process.env.NEXT_PUBLIC_APP_URL}`);
  console.log(`   Currency: USD (based on IremboPay dashboard)`);

  console.log('\n🚀 Next Steps:');
  console.log(
    '1. Complete the product mappings in lib/services/irembopay-product-mapping.ts'
  );
  console.log('2. Run: npx tsx scripts/complete-irembopay-mappings.ts');
  console.log('3. Try making a test booking');
  console.log('4. Check the console logs for payment initialization');
} else {
  console.log('❌ Some environment variables are missing.');

  console.log('\n🔧 To Fix:');
  console.log('Add these to your .env file:');

  if (!process.env.IREMBO_SECRET_KEY) {
    console.log('   IREMBO_SECRET_KEY=your_secret_key_here');
  }

  if (!process.env.IREMBO_PAYMENT_ACCOUNT_ID) {
    console.log(
      '   IREMBO_PAYMENT_ACCOUNT_ID=PI-bd12658823  # Your payment account'
    );
  }

  if (!process.env.NEXT_PUBLIC_APP_URL) {
    console.log('   NEXT_PUBLIC_APP_URL=http://localhost:3000');
  }
}

console.log('\n💡 How the Product Mapping System Works:');
console.log('   → Each tour package ID is mapped to an IremboPay product code');
console.log(
  '   → Product codes are auto-generated by IremboPay (e.g., PC-74ac3ffe8a)'
);
console.log('   → Currency is USD as configured in your IremboPay dashboard');
console.log('   → Prices are taken from the tour package data');

console.log('\n📋 Current Mapping Status:');
console.log('   ✅ Kigali City Tour → PC-74ac3ffe8a');
console.log('   ✅ Akagera National Park Safari → PC-a12f760427');
console.log(
  '   ❌ 6 more tours need mapping (run complete-irembopay-mappings.ts)'
);

console.log('\n📞 Need Help?');
console.log(
  '   → Check IremboPay dashboard for correct payment account (must support USD)'
);
console.log('   → Complete product mappings using the mapping script');
console.log(
  '   → Test with mapped tours first (Kigali City Tour or Akagera Safari)'
);
