export const ErrorCodes = {
  VALIDATION: {
    INVALID_PRICE: 'INVALID_PRICE',
    INVALID_DATE: 'INVALID_DATE',
    INVALID_ITINERARY: 'INVALID_ITINERARY',
    INVALID_TITLE: 'INVALID_TITLE',
    INVALID_DESCRIPTION: 'INVALID_DESCRIPTION',
    INVALID_LOCATION: 'INVALID_LOCATION',
  },
  API: {
    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    SERVER_ERROR: 'SERVER_ERROR',
  },
} as const;
